# Generated by Django 5.2.4 on 2025-07-10 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=20)),
                ('a_img', models.ImageField(upload_to='img')),
                ('joined_date', models.DateField()),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_img', models.ImageField(upload_to='img')),
                ('b_category', models.CharField(max_length=20)),
                ('b_heading', models.TextField()),
                ('b_posted_date', models.DateField(blank=True, null=True)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_img', to='blogapp.author')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to='blogapp.author')),
            ],
        ),
    ]
