# Generated by Django 5.2.4 on 2025-07-11 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_detail',
            name='b_heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_head', to='blogapp.blog'),
        ),
    ]
