# Generated by Django 5.2.4 on 2025-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_detail_b_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='b_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Blog_Detail',
        ),
    ]
