# Generated by Django 5.2.4 on 2025-07-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Phone_no', models.CharField(max_length=20)),
                ('X', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linked_in', models.URLField()),
            ],
        ),
    ]
