# Generated by Django 5.2.4 on 2025-07-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
