# Generated by Django 5.2.4 on 2025-07-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0002_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='open_days',
            field=models.CharField(default='Mon-Sat', max_length=20),
        ),
    ]
