# Generated by Django 5.2.4 on 2025-07-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0003_company_open_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30)),
                ('service_head', models.CharField(max_length=30)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
