# Generated by Django 5.2.4 on 2025-07-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
