# Generated by Django 5.2.4 on 2025-07-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0005_testimonals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonals',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
