# Generated by Django 5.2.4 on 2025-07-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0007_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonals',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
